---
- hosts: webserver
  become: yes
  tasks:
  - name: install java 6 on ubuntu
    apt: 
  - name: "{{myjavaonubuntu}}"
  state: present
  when: ansible_os_family ="debian"

---
- hosts: webserver
  become: yes
  tasks: 
    - name: install java 6 on redhat
      apt:
    - name: "{{myjavaonredhat}}"
  state: present
  when: ansible_os_family ="redhat"

